### ISSUE TITLE
Gradle import not working

### ISSUE THREAD

**Issue by stoefln** [arissa34/Android-Multi-Bluetooth-Library#1]
When I try to import your library I get:

> Error:(25, 13) Failed to resolve: com.ramimartin.multibluetooth:AndroidMultiBluetoothLibrary:1.1-SNAPSHOT

Any ideas?

**Comment by arissa34** [comment]
Hello Stephan,

I tried to import in a new project and it's working very well. Can you show me your build.gradle to help you ?

**Comment by stoefln** [comment]
Thanks for taking a look:

<pre>apply plugin: 'com.android.application'
android {
    compileSdkVersion 22
    buildToolsVersion "22.0.0"
    defaultConfig {
        applicationId "net.microtrash.wisperingtree"
        minSdkVersion 14
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.0.0'
    compile 'com.jakewharton:butterknife:6.0.0'
    compile 'de.greenrobot:eventbus:2.2.0'
    compile 'com.jakewharton:butterknife:6.0.0'
    compile 'com.ramimartin.multibluetooth:AndroidMultiBluetoothLibrary:1.1-SNAPSHOT'
}
</pre>

**Comment by arissa34** [comment]
you need to add this below your dependencies :

``` java
repositories {
    maven {
        url "http://sfdn.ddns.net/maven2/"
    }
} 
```

**Comment by stoefln** [comment]
stupid me, thanks a lot!
