### ISSUE TITLE
gradle maven repository dead

### ISSUE THREAD

**Issue by behelit** [arissa34/Android-Multi-Bluetooth-Library#10]
Using the repo specified on git doesn't seem to work.
I don't know much about how the gradle dependencies are set up but I'm using the following:

`repositories {
    maven {
        url "http://sfdn.ddns.net/maven2/"
    }
    mavenCentral()
}`

I noticed you use a different one altogether in the sample projects but that repo link seems to be dead as well

`repositories {
    maven {
        url "http://192.168.1.99/maven2/"
    }
    mavenCentral()
}`

**Comment by arissa34** [comment]
Gradle and maven repository are now resurrected !
