### ISSUE TITLE
Missing Unit tests

### ISSUE THREAD

**Issue by ewoks** [arissa34/Android-Multi-Bluetooth-Library#13]
How we can rely on this library if there is no single unit test to cover it? Do you trust it? You can't.
Please add unit test so one can easy prove if functionality is as declared. Thanks

**Comment by reixd** [comment]
You are right @ewoks . But if you need the UTs in the next days/weeks I am afraid you need to write them. We do not always have time to write the needed tests.

**Comment by ewoks** [comment]
Why issue is closed if there is still not a single unit test? If it stayed open, somebody could notice it and write some tests if he is interesting in this library..
