### ISSUE TITLE
Without BluetoothActivity & Bluetooth Fragment

### ISSUE THREAD

**Issue by sajid-verveba** [arissa34/Android-Multi-Bluetooth-Library#15]
Hi All,

Can't we create class which can be used for Bluetooth connectivity implementation.

Instead of Bluetooth Activity & Fragment , we can use this class.

Currently I am using App compact so can't use Bluetooth Activity or Fragment.

Open for suggestions & improvement comments.

Best Regards,
Sajid

**Comment by reixd** [comment]
Do you have a patch that can be merged?

**Comment by sajid-verveba** [comment]
not yet ready but i can do it.

**Comment by behelit** [comment]
You can, just call the same functions that the base activity calls.
Look at BluetoothActivity.java
