### ISSUE TITLE
Mac-Addresses of the conntected devices

### ISSUE THREAD

**Issue by TypeOverride** [arissa34/Android-Multi-Bluetooth-Library#19]
I see there is a method for sending directly to one device:
`public void sendBytes(final String adressMacTarget, final byte[] message);`

But i cant figure out where to get the mac address.

Isn't there an thrown event that giving me the mac address of the device that has connected to my server?

**Comment by arissa34** [comment]
You must store all mac addresses by yourself when connection is successful. But keep in mind that only the server knows all clients. If you want to send data, client to client, you have to go through the server.
