### ISSUE TITLE
You can connect with bluetooth HC-06?

### ISSUE THREAD

**Issue by sbarcatt** [arissa34/Android-Multi-Bluetooth-Library#8]
I need to connect to a Bluetooth device HC-06. I can connect as a client with the onDeviceSelectedForConnection ("20: 14: 04: 09: 17: 48") function. It would be possible to connect as Server?

The works they try and not worked is mBluetoothManager.createServeur ("20: 14: 04: 09: 17: 48");

You know someone who has tried to do this? Thank you. Excuse me for my bad english! Greetings and excellent library

**Comment by behelit** [comment]
It doesn't look like the library is set up to allow this.
But couldn't you connect from the HC-06?

This site might help you:
http://robocontroller.ru/news/btca2a_upravlenie_arduino_po_bluetooth_pri_pomoshhi_android/2013-11-16-40

It's in Russian but can be easily translated:
http://www.microsofttranslator.com/bv.aspx?from=&to=en&a=http://robocontroller.ru/news/btca2a_upravlenie_arduino_po_bluetooth_pri_pomoshhi_android/2013-11-16-40
